apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: breno-pod
  name: breno-pod
spec:
  containers:
  - image: nginx
    name: teste-nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
